### PR TITLE
Include title element in index.html

### PR DESCRIPTION
**Pull request by Galbrush**
Proposed a title element in the index.html file.

### CODE REVIEW

**Comment by Galbrush** [comment]
Do you want to have the html 5 logo icon included as well?

**Comment by CorinaMurg** [comment]
@Galbrush That's a good question! 
The title you just added in the head element has a different role than the title we see at the top of the page.
It shows up in the tab, like these two:
image
So I know one tab is the Google page, the other is the GitHub. So when it comes to logos, it will have to be the logo of the owner/creator of the site.

@YuriDevAT Does the club have a logo we could add in the title? If not, let's create one! :rocket:

**Comment by YuriDevAT** [comment]
We can use the YCC logo. But it should be a separate issue anyways. Let's merge this one if we are okay with the title @CorinaMurg

**Comment by CorinaMurg** [comment]
Definitely, this is ready! Thank you @Galbrush! :tada:

**Review by CorinaMurg — APPROVED** [review]
Great job @Galbrush!

**Comment by YuriDevAT** [comment]
Thank you so much for your contribution @Galbrush 🥳

**Pull request merged**
