### PR TITLE
add html tags

### PR DESCRIPTION
**Pull request by TiffanyClark**
I added html tags to js file. this is fun. Thanks!

### CODE REVIEW

**Comment by YuriDevAT** [comment]
Hey @TiffanyClark, thanks for contributing. As written in the issue, **ALL** HTML tags should be in the array. Let me know when you have updated the array with the rest of the tags, so I can merge your PR.

**Comment by TiffanyClark** [comment]
Hi Yuri should I include all the HTML tags we learn in front-end foxes bootcamp?

**Comment by YuriDevAT** [comment]
Hey @TiffanyClark. Here is a [list of all HTML tags](https://www.w3schools.com/tags/default.asp). The deprecated ones are not needed. 🙂 Please be aware that this app will be a game to check how many HTML tags someones knows for accessibility reasons, as it is said in the [`readme.md` file](https://github.com/YurisCodingClub/html-tag-quiz). Therefore, really **all** HTML tags are needed.

**Comment by TiffanyClark** [comment]
@YuriDevAT  Thank you very much for the link. I will include all the tags and finish this today.

**Comment by YuriDevAT** [comment]
Ok @TiffanyClark. Let me know when you are finished 🙂

**Comment by YuriDevAT** [comment]
Thank you so much for contributing 🥳

**Pull request merged**
